[package]
name = "patract-archive"
version = "0.1.0"
authors = ["Patract Labs <https://github.com/patractlabs>"]
edition = "2018"
description = "Indexes the Jupiter and Patract Networks"

[dependencies]
anyhow = "1.0"
clap = { version = "2.33.1", features = ["yaml", "suggestions", "color"] }
ctrlc = { version = "3.1.5", features = ["termination"] }
log = "0.4"
serde = "1.0"
structopt = { version = "0.3", features = ["suggestions", "color"] }
toml = "0.5"

sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }

# patract branch = "archive"
patract-io = { path = "../../../../Work/patractlabs/patract/primitives/io" }
jupiter-runtime = { package = "jupiter-prep-runtime", path = "../../../../Work/patractlabs/patract/runtime/jupiter-prep" }

substrate-archive = { path = "../../substrate-archive", features = ["kafka"] }
